site_name: godfrey

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
      icon: material/brightness-7
      name: Dark Mode
    - scheme: slate
      toggle:
      icon: material/brightness-4
      name: Light Mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google

nav:
  - Start: index.md